### ISSUE TITLE
Missing implementation for routine make.MICRODVD_SUBTITLE_ITEM

### ISSUE THREAD

**Issue by nmaguirre** [nmaguirre/eiffel-subtitle-converter#1]
Routine make from class MICRODVD_SUBTITLE_ITEM has an empty implementation. This routine must be implemented, guided by accompanying unit tests for the routine, and its textual description.

**Comment by nicoboccolini** [comment]
solved in rev. 25aa089edd6487716a0039f71447f9f23eecbfa4
