### ISSUE TITLE
Missing precondition for routine adjust_stop_frame.MICRODVD_SUBTITLE_ITEM

### ISSUE THREAD

**Issue by nmaguirre** [nmaguirre/eiffel-subtitle-converter#10]
Routine adjust_stop_frame from class MICRODVD_SUBTITLE_ITEM has no explicit precondition. This routine must have a specific, explicit, precondition, indicating the acceptable new value as a stop frame.

**Comment by dromero19** [comment]
Solved in rev. ca8f2b2

**Comment by nmaguirre** [comment]
Well done!
