### ISSUE TITLE
Missing poscondition for routine adjust_start_time.SUBRIP_SUBTITLE_ITEM

### ISSUE THREAD

**Issue by dastorga** [nmaguirre/eiffel-subtitle-converter#102]

**Comment by rdegiovanni** [comment]
well done!

**Comment by rdegiovanni** [comment]
Sorry,
You are using the = operator in the postcondition to compare two objects.
You should use the is_equal routine.

**Comment by dastorga** [comment]
Sorry!
Solved in c09ed44b8dd5a4c7ab70432c8de8e3044b5ba6c4

**Comment by nricci** [comment]
Seems fine. Closing for the moment
