### ISSUE TITLE
Missing postcondition for routine make_with_text.SUBRIP_SUBTITLE_ITEM

### ISSUE THREAD

**Issue by damarisg** [nmaguirre/eiffel-subtitle-converter#106]

**Comment by damarisg** [comment]
Solved in rev. ed755b3

**Comment by damarisg** [comment]
Problems with github. I'm sorry! solved in rev. 28d4f5f

**Comment by damarisg** [comment]
github problems, I was updated and did not mark my work. So to really mark rewrote changes. Solved in rev. 4fa43e3

**Comment by nricci** [comment]
You should use is_equal rather than "=" to compare objects. Please change this. I'm removing the resolved tag.

**Comment by damarisg** [comment]
Thanks!! Solved in rev. c1c8b1c

**Comment by nricci** [comment]
Please, correct indentation and divide into multiple labels.

**Comment by damarisg** [comment]
Thanks for the correction..!! Solved in rev.  25a4cf5

**Comment by nricci** [comment]
Thanks
