### ISSUE TITLE
Missing precondition for routine SUBRIP_SUBTITLE_ITEM.make

### ISSUE THREAD

**Issue by nicoboccolini** [nmaguirre/eiffel-subtitle-converter#107]

**Comment by nicoboccolini** [comment]
solved in rev. ee955e51601dfc19f0fba8206ce75c617779aa9f

**Comment by nricci** [comment]
Seems alright. However the precondition is a bit messy. I've proposed to add comparison features in  SUBRIP_SUBTITLE_TIME (see issue #113 ), so that the same result will be achieved with much clearer code (i.e. start < end). Wait for the resolution of issue #113 and update your code accordingly.

**Comment by nicoboccolini** [comment]
solved in rev. 4bfca1cb2b63cca2b55da17461f5878125a87265

**Comment by nricci** [comment]
Well done. Thanks
