### ISSUE TITLE
Missing poscondition for routine SUBRIP_SUBTITLE_ITEM.make

### ISSUE THREAD

**Issue by nicoboccolini** [nmaguirre/eiffel-subtitle-converter#108]

**Comment by nicoboccolini** [comment]
resolved in rev. 56d71fad6c3a98c06d1ed46302b4c2dc5c07f42f

**Comment by rdegiovanni** [comment]
The expression text.is_empty=true is redundant. You can use directly text.is_empty.
In addition, remember we require that constants in Eiffel should have the first letter in uppercase (e.g., True and False.

**Comment by nicoboccolini** [comment]
Thanks! Solved in rev. 0900b12816d6ac170b83c64618d589029bae6297

**Comment by nicoboccolini** [comment]
i'm sorry! solved in rev. b194db5fc3f1f5a593ac75432f576a1bb68c66f8

**Comment by nricci** [comment]
Well Done!

**Comment by rdegiovanni** [comment]
You are using = to compare SUBRIP_SUBTITLE_TIME objects. You should use the is_equal routine.

**Comment by nicoboccolini** [comment]
Thanks! fixed in rev. 1cee6f017186166db2b1875edbcd23f8510a8ef3

**Comment by nricci** [comment]
Thanks! Closing for the moment.
