### ISSUE TITLE
Missing unit tests for routine adjust_stop_frame.MICRODVD_SUBTITLE_ITEM

### ISSUE THREAD

**Issue by nmaguirre** [nmaguirre/eiffel-subtitle-converter#11]
Routine adjust_stop_frame from class MICRODVD_SUBTITLE_ITEM has no unit tests to assess its behaviour. At least one unit "positive" and one "negative" unit test must be provided for this routine. In this context, 'positive' is a test that evaluates the correct behaviour of the routine when right arguments are passed, while 'negative' refers to tests that check that the routine correctly controls ill-formed direct or indirect inputs.

Please use a fine grained granularity for the tests. If you want to assert several things on the same situation, please provide different tests for each assert. See tests for make.MICRODVD_SUBTITLE_ITEM for an example.

**Comment by marianoruano** [comment]
Resolved in rev 37adf8a

**Comment by marianoruano** [comment]
Correction name of tests in rev 7c350c6

**Comment by marianoruano** [comment]
Fixed ir rev 34906b2

**Comment by nmaguirre** [comment]
Tests are alright, but note tag "testting", with tt instead of t, is wrong. Please correct. Removing the 'resolved' tag.

**Comment by marianoruano** [comment]
Correction test in rev 4314547
