### ISSUE TITLE
Missing implementation for routine repOK.SUBRIP_SUBTITLE

### ISSUE THREAD

**Issue by andruvetto** [nmaguirre/eiffel-subtitle-converter#110]
Routine repOK from class SUBRIP_SUBTITLE has an empty implementation.

**Comment by andruvetto** [comment]
Solved in 3c9f3e2.  Obviously be solved the issue #113

**Comment by nmaguirre** [comment]
Project does not compile. Please correct asap.

**Comment by andruvetto** [comment]
solved in 77963c2

**Comment by miri15** [comment]
Does not create the object prev_stop_time. Should compare each value tuple .There is more than one case. Correct me if I'm wrong.

**Comment by andruvetto** [comment]
not need to create the object because " prev_stop_time " is used for reference only. All cases are contemplated. Removing the labels bug. If you have any other question let me know

**Comment by miri15** [comment]
Sorry. Is correct!  The class "SUBRIP_SUBTITLE_TIME"  inherit from COMPARABLE. I was wrong.

**Comment by rdegiovanni** [comment]
Well done.
