### ISSUE TITLE
Missing postcondition for routine repOK.SUBRIP_SUBTITLE

### ISSUE THREAD

**Issue by andruvetto** [nmaguirre/eiffel-subtitle-converter#112]

**Comment by andruvetto** [comment]
solved in 5fe5965

**Comment by andruvetto** [comment]
fixed b8949ac

**Comment by nricci** [comment]
Result is a boolean value and thus is an expanded class. Expanded clases instances can't be void so the test is redundant. I would delete the postcondition altogether.

**Comment by andruvetto** [comment]
solved in e79fef3
