### ISSUE TITLE
Missing unit test for routine flush.SUBRIP_SUBTITLE_TESTS

### ISSUE THREAD

**Issue by mromina** [nmaguirre/eiffel-subtitle-converter#116]

**Comment by mromina** [comment]
Solved in rev. f15c1b9

**Comment by rdegiovanni** [comment]
The variable flag is redundant in your test. Remove it.
 Please, add a more relevant assertion, e.g., check if after executing the routine flush, the number of elements is 0.

**Comment by mromina** [comment]
Change in the visibility of feature 'items' to do the test 'test_valid_flush'. Solved in rev. 854f815.
Modification of test 'test_valid_flush'. Resolved in rev.  258ae46

**Comment by saiema** [comment]
The check **subrip_sub.items.count /= 0** is not necessary, if this condition is false then the **add_subtitle_item** routine has a bug but this shouldn't be tested in this test.

**Comment by mromina** [comment]
Resolved in rev. 4d54235.
