### ISSUE TITLE
New routine time_millisecond in SUBRIP_SUBTITLE_TIME

### ISSUE THREAD

**Issue by guttlein** [nmaguirre/eiffel-subtitle-converter#122]
Making this new routine. It have to count the total time in milliseconds

**Comment by guttlein** [comment]
Solved in 8bdef22bdf5416c94ae5bf549962a98973e1b572

**Comment by saiema** [comment]
The issue is solved in ea3f074

**Comment by saiema** [comment]
Resolved and closed
