### ISSUE TITLE
Missing postcondition for routine add_subtitle_item.SUBRIP_SUBTITLE

### ISSUE THREAD

**Issue by gamassimino** [nmaguirre/eiffel-subtitle-converter#124]

**Comment by gamassimino** [comment]
solved in rev. 4fa695e

**Comment by gamassimino** [comment]
the postcondition was wrong, fixed in rev. 3fb4fb1

**Comment by rdegiovanni** [comment]
Your are using = to compare objects. Please be sure to use the is_equal routine.

**Comment by gamassimino** [comment]
corrected in rev .a71ed11

**Comment by rdegiovanni** [comment]
The routine is_equal already returns a boolean value, so it's redundant to compare its result with True. 
Remove the comparison with constant True.
In addition, remember that our conventions indicates that constants should start with a capital letter.

**Comment by gamassimino** [comment]
okey, corrected in rev. a3ec252

**Comment by rdegiovanni** [comment]
well done.
