### ISSUE TITLE
Missing precondition for routine SUBRIP_SUBTITLE.flush

### ISSUE THREAD

**Issue by ezedepetris** [nmaguirre/eiffel-subtitle-converter#127]

**Comment by ezedepetris** [comment]
Resolved in rev 87db6e9

**Comment by andruvetto** [comment]
Please check this precondition, the project does not compile for any error in it

**Comment by ezedepetris** [comment]
i removing the precondition, the routine wipe_out check that, Resolved in rev 053c704

**Comment by rdegiovanni** [comment]
Consider to add a class invariant requiring that items should never be Void.
Now, I close this issue.
