### ISSUE TITLE
Missing precondition for routine remove_items.SUBRIP_SUBTITLE 

### ISSUE THREAD

**Issue by nicodomgz** [nmaguirre/eiffel-subtitle-converter#128]

**Comment by vikibueno** [comment]
Solved in rev. d7559c5

**Comment by rdegiovanni** [comment]
Additionally require that both parameters start_time and stop_time be different that Void.
This new precondition should be placed first, before the current one.

**Comment by vikibueno** [comment]
Solved in rev. 3ed3edc

**Comment by rdegiovanni** [comment]
well done.
