### ISSUE TITLE
Missing postcondition for routine adjust_stop_frame.MICRODVD_SUBTITLE_ITEM

### ISSUE THREAD

**Issue by nmaguirre** [nmaguirre/eiffel-subtitle-converter#13]
Routine adjust_stop_frame from class MICRODVD_SUBTITLE_ITEM has no explicit postcondition. This routine must have a specific, explicit, postcondition, indicating how the state of the item is set by the routine.

**Comment by lukax77** [comment]
Resolved in rev. f08d653
