### ISSUE TITLE
Missing postcondition on routine repOk for class MICRODVD_SUBTITLE

### ISSUE THREAD

**Issue by guttlein** [nmaguirre/eiffel-subtitle-converter#130]
Postcondition for repOk is missing. Doing it!

**Comment by guttlein** [comment]
solved in 7a00b6bcb39e50857518bfa7fa33f1f0635f5ae2

**Comment by rdegiovanni** [comment]
Irrelevant postcondition (Result or not Result). 
Please modify it to express something more important, or just remove it.

**Comment by guttlein** [comment]
solved on fa149b110555f061ba188c9a43eff7583472e30c

**Comment by saiema** [comment]
Result can't be void (the routine should return a detachable BOOLEAN to allow Void results)

Adding label Invalid.
