### ISSUE TITLE
Missing unit test for routine is_less.SUBRIP_SUBTITLE_TIME

### ISSUE THREAD

**Issue by dahue** [nmaguirre/eiffel-subtitle-converter#131]

**Comment by dahue** [comment]
Solved in 1b01b67

**Comment by andruvetto** [comment]
fixed in 688eb383

**Comment by rdegiovanni** [comment]
Please add more relevant tests for this feature.
For example, when current_time is greater that other_time.

**Comment by dahue** [comment]
Solved in 0bb4aa8c0c673e6167469b02628b186c6f165587

**Comment by rdegiovanni** [comment]
Please correct your tests: test_is_less_first and test_is_less_second. 
The asserts you wrote don't correspond to what you are trying to test.

Try to assign more representative names to your test cases, not just first, second, ...

**Comment by dahue** [comment]
Sorry! Fixed in 38b6fad20d7e94b805204b4a5f816420f0b1245a

**Comment by nricci** [comment]
Well done.
