### ISSUE TITLE
Missing invariant from class SUBRIP_SUBTITLE_ITEM

### ISSUE THREAD

**Issue by lukax77** [nmaguirre/eiffel-subtitle-converter#133]
Class invariants capture global properties of the class. They are consistency constraints applicable to all instances of a class.

**Comment by lukax77** [comment]
Resolved in rev. f6cb0a9

**Comment by rdegiovanni** [comment]
Additionally you should require that the attribute text cannot be Void.

**Comment by lukax77** [comment]
Thanks for your notice.
Resolved in rev. b56d39f

**Comment by rdegiovanni** [comment]
well done.
