### ISSUE TITLE
Missing unit test for routine is_ready_to_convert.CONVERTER_LOGIC

### ISSUE THREAD

**Issue by gamassimino** [nmaguirre/eiffel-subtitle-converter#135]

**Comment by gamassimino** [comment]
solved in rev. 140fe7e

**Comment by gamassimino** [comment]
fixed in rev. b5b7f09

**Comment by saiema** [comment]
You are not checking is_ready_to_convert (there is no call to this feature)

A correct assert should be **converted.is_ready_to_convert**, you are expecting that the feature return **True**. You are testing **converter.set_source(MICRODVD_SUBTITLE)**.

The invalid test has the same problem.

**Comment by gamassimino** [comment]
But in a test, I shouldn't use the same feature that I'm testing because it is exactly what I want to try
Also, if the feature "source" has something of type "SUBTITLE" and the feature "targer" is Void, then the subtitle is ready to convert, because I did this assert

**Comment by gamassimino** [comment]
fixed in rev. 21413f0

**Comment by saiema** [comment]
Please use **not** instead of **= False**.

**Comment by gamassimino** [comment]
fixed in rev. e97e73b

**Comment by saiema** [comment]
In test **test_is_ready_to_convert_with_not_subtitle** the variable **passed** is never used.

**Comment by gamassimino** [comment]
fixed in rev. b722e78
