### ISSUE TITLE
Misssing implementation for routine CONVERTER_LOGIC.is_ready_to_convert

### ISSUE THREAD

**Issue by nicoboccolini** [nmaguirre/eiffel-subtitle-converter#136]

**Comment by nicoboccolini** [comment]
Solved in rev. b2bddbff486472b5058165316fd04c2d5a32d7ae

**Comment by saiema** [comment]
You should just return the condition inside the if.

**Comment by nicoboccolini** [comment]
Solved in rev. 49e762d0c9f757f2520bf882253cf52713953446
