### ISSUE TITLE
Missing unit tests for routine make_with_text.MICRODVD_SUBTITLE_ITEM

### ISSUE THREAD

**Issue by nmaguirre** [nmaguirre/eiffel-subtitle-converter#15]
Routine make_with_text from class MICRODVD_SUBTITLE_ITEM has no unit tests to assess its behaviour. At least one unit "positive" and one "negative" unit test must be provided for this routine. In this context, 'positive' is a test that evaluates the correct behaviour of the routine when right arguments are passed, while 'negative' refers to tests that check that the routine correctly controls ill-formed direct or indirect inputs.

Please use a fine grained granularity for the tests. If you want to assert several things on the same situation, please provide different tests for each assert. See tests for make.MICRODVD_SUBTITLE_ITEM for an example.

**Comment by miri15** [comment]
Tests implementation only for positive cases. Only missing negative cases. Solved in rev. ae0995d

**Comment by miri15** [comment]
Test implementation for negative cases. Solved in rev. 3a34b0a

**Comment by miri15** [comment]
Test implementation for negative cases (equal frames). Solved in rev 8de4719

**Comment by nmaguirre** [comment]
I can think of one more (negative) test: one in which you call make_with_text with valid frame values, but Void text. Please add this test.

**Comment by miri15** [comment]
Negative case added. Solved in rev 9242b04

**Comment by nmaguirre** [comment]
Well done!
