### ISSUE TITLE
Missing Implementation for routine SUBRIP_SUBTITLE.out

### ISSUE THREAD

**Issue by ibongiovanni** [nmaguirre/eiffel-subtitle-converter#153]

**Comment by ibongiovanni** [comment]
Resolved in rev f1692f1

**Comment by ibongiovanni** [comment]
Modified in rev e0d5c89

**Comment by saiema** [comment]
The solution is correct but the implementation of **SUBRIP_SUBTITLE_ITEM.out** should have been made in another issue.
