### ISSUE TITLE
Missing implementation for routine set_text.MICRODVD_SUBTITLE_ITEM

### ISSUE THREAD

**Issue by rdegiovanni** [nmaguirre/eiffel-subtitle-converter#16]
Routine set_text from class MICRODVD_SUBTITLE_ITEM has an empty implementation. This routine must be implemented, guided by its textual description.

**Comment by ezedepetris** [comment]
Resolved in rev ffd0e91

**Comment by ezedepetris** [comment]
Resolved in rev 4ad5b26

**Comment by nmaguirre** [comment]
Well done!
