### ISSUE TITLE
Missing implementation for routine has_loaded_subrip_subtitle.CONVERTER_LOGIC

### ISSUE THREAD

**Issue by ibongiovanni** [nmaguirre/eiffel-subtitle-converter#165]
This routine has to return True if source is a SUBRIP_SUBTITLE, and otherwise return False

**Comment by ibongiovanni** [comment]
Solved in rev b0bab41

**Comment by nricci** [comment]
Its okay. But you solved two issues in one commit. (You solved this issue and #148 with the same commit). For tracking purposes it is better if you solve them and commit them separately.
