### ISSUE TITLE
Missing implementation for routine SUBRIP_SUBTITLE_ITEM.make_from_string

### ISSUE THREAD

**Issue by lukax77** [nmaguirre/eiffel-subtitle-converter#169]
There should be a routine that takes as a parameter two strings and initialize the subrip_subtitle_item attributes (start_time, stop_time, text) .
The first parameter must be the timecode format used is hours:minutes:seconds,milliseconds, the time that the subtitle should appear on the screen, followed by --> and the time it should disappear.
The second parameter must be the subtitle text.

**Comment by lukax77** [comment]
Resolved in rev. c32510b

**Comment by nricci** [comment]
Well done. Thanks!
