### ISSUE TITLE
Missing unit tests for routine set_text.MICRODVD_SUBTITLE_ITEM

### ISSUE THREAD

**Issue by rdegiovanni** [nmaguirre/eiffel-subtitle-converter#17]
Routine set_text from class MICRODVD_SUBTITLE_ITEM has no unit tests to assess its behaviour. At least one "positive" and one "negative" unit test must be provided for this routine. In this context, 'positive' is a test that evaluates the correct behaviour of the routine when right arguments are passed, while 'negative' refers to tests that check that the routine correctly controls ill-formed direct or indirect inputs.

Please use a fine grained granularity for the tests. If you want to assert several things on the same situation, please provide different tests for each assert. See tests for make.MICRODVD_SUBTITLE_ITEM for an example.

**Comment by mromina** [comment]
Solved in rev. 8d2dff8

**Comment by nmaguirre** [comment]
Two small things to correct. First, in the note, change testting --> testing. Second, in test_invalid_set_text,  indicate in the comment why the test fails (essentially, because you are setting the text with Void, and that is not allowed). Thanks. I'm removing the 'resolved' tag.

**Comment by mromina** [comment]
Modification in the comment and note of test. Solved in rev. 0e6c658

**Comment by nmaguirre** [comment]
Well done!
