### ISSUE TITLE
Missing Implementation for routine SUBRIP_SUBTITLE_TIME.out

### ISSUE THREAD

**Issue by ibongiovanni** [nmaguirre/eiffel-subtitle-converter#176]

**Comment by ibongiovanni** [comment]
Resolved in rev 50cb95c

**Comment by nricci** [comment]
I'm not sure that the feature will always print something like "hh:mm:ss,mmm". For instance if I do:

create time.make_with_values(1,1,1,1)

then time.out will print "1:1:1,1" rather than "01:01:01,001"

**Comment by ibongiovanni** [comment]
I did some changes and additions for solve that issue in rev ff55ffd

**Comment by ibongiovanni** [comment]
Fixed in rev 1463f59
