### ISSUE TITLE
Missing precondition for routine set_text.MICRODVD_SUBTITLE_ITEM

### ISSUE THREAD

**Issue by rdegiovanni** [nmaguirre/eiffel-subtitle-converter#18]
Routine set_text from class MICRODVD_SUBTITLE_ITEM has no explicit precondition. This routine must have a specific precondition indicating the acceptable new value for the text.

**Comment by mromina** [comment]
Solved in rev. 8d2dff8

**Comment by nmaguirre** [comment]
Void is a constant, and according to Eiffel's conventions, it should start with a capital letter (Void). 

The tag in the precondition has nothing to do with what is being checked. Why not put something like new_text_not_void: ...

I'm removing the 'resolved' tag.

**Comment by mromina** [comment]
Modification in the tag of precondition. Solved in rev. e5d339f

**Comment by nmaguirre** [comment]
Well done!
