### ISSUE TITLE
Missing implementation for the routine CONVERTER_LOGIC.make_with_microdvd_subtitle

### ISSUE THREAD

**Issue by ezedepetris** [nmaguirre/eiffel-subtitle-converter#180]

**Comment by ezedepetris** [comment]
Resolved in rev 4a8129a and 690e17a

**Comment by gamassimino** [comment]
you should consider the case that the file of subtitle is wrong and you should set "last_load_success" with the values True or False

**Comment by ezedepetris** [comment]
Resolved in rev cf72142 :beer:
