### ISSUE TITLE
Missing implementation for routine CONVERTER_LOGIC.make_with_subrip_subtitle

### ISSUE THREAD

**Issue by lukax77** [nmaguirre/eiffel-subtitle-converter#181]
There should be a routine that takes as a parameter a filename and initialize the source with a loaded subtitle of type SUBRIP_SUBTITLE.

**Comment by lukax77** [comment]
Resolved in rev. 810d5ef

**Comment by gamassimino** [comment]
you should consider the case that the file of subtitle is wrong and you should set "last_load_success" with the values True or False

**Comment by nricci** [comment]
What happens if the file contains ill-formatted data?

**Comment by lukax77** [comment]
Resolved in rev. 6682a0f
