### ISSUE TITLE
Missing postcondition for the routine CONVERTER_LOGIC.make_with_microdvd_subtitle

### ISSUE THREAD

**Issue by ezedepetris** [nmaguirre/eiffel-subtitle-converter#185]

**Comment by ezedepetris** [comment]
Resolved in rev 216be38

**Comment by nricci** [comment]
I don't think you can assert that source will necessarily be /= Void. What happens if the file is ill-formated? Probably it is better to say that source will be non void and last_load_succeded, or either it'll be be void and last_load_succeded will be false

**Comment by ezedepetris** [comment]
okey, i resolved in the rev 0e1696b
