### ISSUE TITLE
Missing postcondition for routine set_text.MICRODVD_SUBTITLE_ITEM

### ISSUE THREAD

**Issue by rdegiovanni** [nmaguirre/eiffel-subtitle-converter#19]
Routine set_text from class MICRODVD_SUBTITLE_ITEM has no explicit postcondition. This routine must have a specific, explicit, postcondition, indicating how the state of the item is set by the routine.

**Comment by mromina** [comment]
Solved in rev. 8d2dff8

**Comment by nmaguirre** [comment]
Please add a tag to the postcondition. It could be 'text_is_set: ... '. I'm removing the 'resolved' tag.

**Comment by mromina** [comment]
Added tag in the postcondition. Solved in rev. 5cfec3b

**Comment by nmaguirre** [comment]
Well done!
