### ISSUE TITLE
Missing implementation for routine CONVERTER_LOGIC.set_target

### ISSUE THREAD

**Issue by miri15** [nmaguirre/eiffel-subtitle-converter#193]

**Comment by miri15** [comment]
Resolved in rev. b2f02c8

**Comment by nricci** [comment]
I don't think target is something that you should be setting externally but rather it will get set whenever a subtitle is converted. This feature is not necessary. Please remove it.

**Comment by nricci** [comment]
In fact it is not good practice to just remove it. Mark it as obsolete with message "To be deleted: Unnecessary feature."

**Comment by miri15** [comment]
Ok. Corrected in rev. 3ded9bc
