### ISSUE TITLE
Incomplete implementation of scenario INITIALISATION_FEATURE.system_start_with_subrip_subtitle

### ISSUE THREAD

**Issue by damarisg** [nmaguirre/eiffel-subtitle-converter#200]
Must implement scenario INITIALISATION_FEATURE.system_start_with_subrip_subtitle .
This issue will be resolved in branch initialisation_feature by [Dámaris Gomez](https://github.com/damarisg) and  [Nicolás Dominguez](https://github.com/nikd93)

**Comment by nicodomgz** [comment]
system_start_with_subrip_subtitle already implemented.
