### ISSUE TITLE
Missing postcondition for routine change_fps.MICRODVD_SUBTITLE

### ISSUE THREAD

**Issue by andruvetto** [nmaguirre/eiffel-subtitle-converter#25]

**Comment by andruvetto** [comment]
resolved in 8ecbb48

**Comment by nmaguirre** [comment]
Please add a tag to the postcondition. Removing 'resolved' tag.

**Comment by nmaguirre** [comment]
Please add 12 as a constant, instead of referring to the "magic" number. Define a feature:

min_valid_fps: INTEGER = 12

and add an appropriate comment to it. Then, in the precondition, use min_valid_fps instead of directly using 12. Thanks! Removing the 'resolved' tag, for the moment...

**Comment by andruvetto** [comment]
Sorry, I think your comment refers to another issue. Tag to the postcondition was added in ca619b4c

**Comment by nmaguirre** [comment]
You are right! Still, the tag is inappropriate. should be something like "fps_set". Please change.

**Comment by andruvetto** [comment]
solved in b92c73e

**Comment by nmaguirre** [comment]
Well done!
