### ISSUE TITLE
Missing Precondition from routine 	remove_items.MICRODVD_SUBTITLE

### ISSUE THREAD

**Issue by GastonPalandri** [nmaguirre/eiffel-subtitle-converter#26]

**Comment by GastonPalandri** [comment]
Solved in rev. f3ae953

**Comment by GastonPalandri** [comment]
Change precondition. Solved in rev. 3a6c6d2

**Comment by GastonPalandri** [comment]
change rev. be4bee7

**Comment by nmaguirre** [comment]
Please add the appropriate labels (specification). Require clause is not correctly indented. Expression 
 valid_items = item.count /= 0 does not make sense. What is "valid_items"? The label? Then use ":", not "=". What is item? It does not exist.

**Comment by GastonPalandri** [comment]
Change rev. d3a1a25

**Comment by GastonPalandri** [comment]
modific routine remove_items. rev 8717811

**Comment by nricci** [comment]
It is better if you put the two terms of the conjunction in separate labels. Also the second rev number that you posted is wrong, it does not reflect the changes concerned to this issue.

**Comment by GastonPalandri** [comment]
change rev. a90ba2e

**Comment by nricci** [comment]
Well done! Thanks
