### ISSUE TITLE
Missing implementation for routine MICRODVD_SUBTITLE.make

### ISSUE THREAD

**Issue by ezedepetris** [nmaguirre/eiffel-subtitle-converter#27]

**Comment by ezedepetris** [comment]
Resolved in rev f4c0b68

**Comment by nmaguirre** [comment]
Implementation is wrong. repOK is a routine, not an object. Feature frames_per_second is a REAL, no need to call create. It should receive some appropriate default value. Smallest acceptable value is 23.97 (below that you woudn't see the movie as a continuous stream). I'm removing the resolved tag.

**Comment by ezedepetris** [comment]
Resolved in rev d275384
