### ISSUE TITLE
Missing postcondition for routine make.MICRODVD_SUBTITLE_ITEM

### ISSUE THREAD

**Issue by nmaguirre** [nmaguirre/eiffel-subtitle-converter#3]
Routine make from class MICRODVD_SUBTITLE_ITEM has no explicit postcondition. This routine must have a specific, explicit, postcondition, indicating how the state of the item is set by the constructor.

**Comment by guttlein** [comment]
solved on f04c269104b393c8b743c69cc60b5ac697a496d5
