### ISSUE TITLE
Missing unit test for routine remove_items.MICRODVD_SUBTITLE

### ISSUE THREAD

**Issue by jicibils** [nmaguirre/eiffel-subtitle-converter#31]

**Comment by jicibils** [comment]
Resolved in rev. 5f2f4c5 and 3c1d455 and df41ace

**Comment by nricci** [comment]
Please, for the next time, provide only one rev number, referring to the commit in which you included the tests. Tests are ok. But I think you should provide more tests like test_remove_items_valid to exercise all posible scenarios of items removal. Try to think of more cases (in item overlaps with one/both borders, touches exactly one/both bordes, is totally or partially included in within the borders, the time frame given could contain no items). Sorry to be picky but this is a very important feature and should be tested accordingly.

**Comment by jicibils** [comment]
resolved in rev ae101ff

**Comment by nricci** [comment]
Great! Thanks
