### ISSUE TITLE
Missing postcondition for routine MICRODVD_SUBTITLE.flush

### ISSUE THREAD

**Issue by ibongiovanni** [nmaguirre/eiffel-subtitle-converter#33]

**Comment by ibongiovanni** [comment]
Solved in rev f198b86

**Comment by nmaguirre** [comment]
Please add an appropriate tag to your postcondition. Thanks!

**Comment by ibongiovanni** [comment]
Someone else already added a tag for the postcondition so I'm adding the resolved tag
