### ISSUE TITLE
Missing implementation for routine repOK.MICRODVD_SUBTITLE

### ISSUE THREAD

**Issue by lukax77** [nmaguirre/eiffel-subtitle-converter#35]
Routine repOK from class MICRODVD_SUBTITLE has an empty implementation.

**Comment by dromero19** [comment]
This routine doesn't exist, 'repOK' is a boolean variable of the class.

**Comment by lukax77** [comment]
When implementing a complex abstract data type, it is often helpful to write a function internal to the module that checks that the rep invariant holds. This function can provide an additional level of assurance about your reasoning the correctness of the code. By convention we will call this function repOK.

**Comment by dromero19** [comment]
Sorry, you're right. Thanks for your comment.

**Comment by lukax77** [comment]
Resolved in rev. 350b34f

**Comment by nmaguirre** [comment]
Constants must have the first letter as a capital (True, instead of true). Please solve this problem. Also, make sure that the list does not have void elements stored in it. Removing the 'resolved' tag.

**Comment by lukax77** [comment]
Resolved in rev. 3fb44f9

**Comment by nmaguirre** [comment]
Well done. Still, res = False can be more concisely written as not res.

**Comment by lukax77** [comment]
The routine don't pass one test, therefore I corrected the routine.
Resolver in rev. 251cd7b
