### ISSUE TITLE
Missing precondition for routine add_subtitle_item.MICRODVD_SUBTITLE

### ISSUE THREAD

**Issue by sigarcia** [nmaguirre/eiffel-subtitle-converter#37]

**Comment by sigarcia** [comment]
Solved in rev. 3ae6e95

**Comment by saiema** [comment]
Missing condition in the precondition to check that start_frame should be >= 0

**Comment by sigarcia** [comment]
Correction for precondition. Solved in rev. 6574d14

**Comment by nricci** [comment]
You could split start_frame >= 0 and start_frame < stop_frame into to separate labels.

**Comment by sigarcia** [comment]
Change in rev. 69b8a2e
