### ISSUE TITLE
Missing implementation for routine make_with_text.MICRODVD_SUBTITLE_ITEM

### ISSUE THREAD

**Issue by nmaguirre** [nmaguirre/eiffel-subtitle-converter#4]
Routine make_with_text from class MICRODVD_SUBTITLE_ITEM has an empty implementation. This routine must be implemented, guided by its textual description.

**Comment by arangue** [comment]
Resolved in rev. 38dea03685dba00a9412a17c28f7940c4921d13e

**Comment by nmaguirre** [comment]
Well done!
