### ISSUE TITLE
Missing implementation for routine SUBRIP_SUBTITLE_TIME.make_with_values

### ISSUE THREAD

**Issue by nicoboccolini** [nmaguirre/eiffel-subtitle-converter#44]
Routine make_with_values from class SUBRIP_SUBTITLE_TIME has an empty implementation. This routine must be implemented, guided by its textual description.

**Comment by ezedepetris** [comment]
i create the same routine  a few minutes before you

**Comment by nicoboccolini** [comment]
you were wrong with tittle of the issue! solved in rev. 2badad681e0e5e84d9a1f1f9106840a8b18617e6

**Comment by nricci** [comment]
Thanks!
