### ISSUE TITLE
Missing precondition for routine SUBRIP_SUBTITLE_TIME.set_minute

### ISSUE THREAD

**Issue by LfLanzoni** [nmaguirre/eiffel-subtitle-converter#47]

**Comment by LfLanzoni** [comment]
Solved in 4938a32

**Comment by nricci** [comment]
It's ok but correct code indentation would be:

require
     (new_minute < 60) and (new_minute >= 0)
do
     ....

You must label the precondition as well.

**Comment by LfLanzoni** [comment]
Sorry, solved c0fcd0fe665c7621ed206ec075f3ba05d8253926

**Comment by saiema** [comment]
precondition label is still missing

**Comment by LfLanzoni** [comment]
Sorry, solved 85f11eb506332e495c2e2b1882e685f4255b1292
