### ISSUE TITLE
Missing implementation for routine make.SUBRIP_SUBTITLE_TIME

### ISSUE THREAD

**Issue by damarisg** [nmaguirre/eiffel-subtitle-converter#49]

**Comment by damarisg** [comment]
everything is set to zero by default

**Comment by nricci** [comment]
You shouldn't close your own issues, especially without supplying a rev. nro. Nevertheless, this creation feature is redundant. Please mark as obsolete, default_create should be called instead.

**Comment by damarisg** [comment]
Solved in rev. f9befb8

**Comment by nricci** [comment]
Well done. Thanks!
