### ISSUE TITLE
Missing postcondition for routine make_with_text.MICRODVD_SUBTITLE_ITEM

### ISSUE THREAD

**Issue by nmaguirre** [nmaguirre/eiffel-subtitle-converter#5]
Routine make_with_text from class MICRODVD_SUBTITLE_ITEM has no explicit postcondition. This routine must have a specific, explicit, postcondition, indicating how the state of the item is set by the constructor.

**Comment by dromero19** [comment]
It is implemented but nobody said who did it.

**Comment by nmaguirre** [comment]
It you go to the code, open the file and press "blame", it tells you who did it. It was gamassimino. 

You are right. This is wrong, in the sense that if you are solving an issue, you should state that you are doing so! Well spotted. Thanks. I'm closing the issue.
