### ISSUE TITLE
Missing precondition for routine set_hour.SUBRIP_SUBTITLE_TIME

### ISSUE THREAD

**Issue by vikibueno** [nmaguirre/eiffel-subtitle-converter#50]

**Comment by vikibueno** [comment]
Solved in rev. 091268b

**Comment by nmaguirre** [comment]
Please notice that project does not compile. You made a mistake when writing >=. Please correct asap! Removing resolved tag.

**Comment by vikibueno** [comment]
Solved in rev. 590420b

**Comment by nricci** [comment]
Please correct indentation and provide labels for the pre.

**Comment by vikibueno** [comment]
Fixed up in rev. 2d2a94a

**Comment by saiema** [comment]
hours are not required to be less than 24. You should just give the precondition of >= 0

**Comment by vikibueno** [comment]
Fixed up in rev. 4454b95
