### ISSUE TITLE
Missing postcondition for routine make.SUBRIP_SUBTITLE_TIME

### ISSUE THREAD

**Issue by guttlein** [nmaguirre/eiffel-subtitle-converter#53]
Postcondition for make in SUBRIP_SUBTITLE_TIME class is missing!

**Comment by guttlein** [comment]
Solved on 985d7e495094e62e345aaec8854d6b3698cb4bdb

**Comment by nricci** [comment]
Wrong rev nro. you posted the hash num of the merge instead of the commit that you made the changes in. Closing the issue. Thanks!
