### ISSUE TITLE
Missing implementation for routine SUBRIP_SUBTITLE_TIME.move_forward

### ISSUE THREAD

**Issue by nicoboccolini** [nmaguirre/eiffel-subtitle-converter#56]

**Comment by nicoboccolini** [comment]
resolved in rev. 5064ada9435e7acf0c735ec11dd9bddc1fe979e9

**Comment by nicoboccolini** [comment]
fixed the variable name! resolved en rev. c1ad688c0c512fedf8de25104172ca286fe31699

**Comment by nricci** [comment]
Seems ok. Although the tests are not passing. I think both the implementation and the tests are reasonable. Probably the postcondition is wrong. Closing for now
