### ISSUE TITLE
Missing implementation for routine SUBRIP_SUBTITLE_TIME.set_milliseconds

### ISSUE THREAD

**Issue by dromero19** [nmaguirre/eiffel-subtitle-converter#57]

**Comment by dromero19** [comment]
Solved by @damarisg

**Comment by nricci** [comment]
I don't understand. Its solved by someone else and there is no rev nro provided.

**Comment by dromero19** [comment]
Sorry, is a duplicate issue. It was resolved in the issue #41 with this rev. number cb5e465 by @damarisg.

**Comment by nricci** [comment]
Ok. Didn't notice that. Thanks!
