### ISSUE TITLE
Missing precondition for routine make_with_text.MICRODVD_SUBTITLE_ITEM

### ISSUE THREAD

**Issue by nmaguirre** [nmaguirre/eiffel-subtitle-converter#6]
Routine make_with_text from class MICRODVD_SUBTITLE_ITEM has no explicit precondition. This routine must have a specific, explicit, precondition, indicating the acceptable values for start and stop frames, and the provided text.

**Comment by dahue** [comment]
Solved in a22fa75

**Comment by dahue** [comment]
precondition is not complete.

**Comment by dahue** [comment]
Solved in c52a467

**Comment by nmaguirre** [comment]
There are various problems with the precondition. It's a long "and" chain, that you should split in labelled smaller preconditions. Conditions such as "new_start_frame /= Void" are redundant, and must be eliminated (since new_start_frame is an expanded integer, it cannot be Void). The new_stop_frame must be strictly greater than new_start_frame (don't use <= for comparison in this case, use < instead).

I'm removing the 'resolved' tag.

**Comment by dahue** [comment]
Solved in 5384bef

**Comment by nmaguirre** [comment]
Well done!
