### ISSUE TITLE
Missing unit test for routine set_milliseconds.SUBRIP_SUBTITLE_TIME

### ISSUE THREAD

**Issue by marianoruano** [nmaguirre/eiffel-subtitle-converter#68]

**Comment by marianoruano** [comment]
Solved in rev. d316ccd

**Comment by damarisg** [comment]
Tests are alright, but note tag "testting", with tt instead of t, is wrong and note "se_milliseconds", with "se_" instead of  "set_". Please correct. Removing the 'resolved' tag.

**Comment by marianoruano** [comment]
Correction test rev in rev 4681e91

**Comment by nricci** [comment]
It seems that your commit erased tests of set_seconds.

**Comment by marianoruano** [comment]
Erased test restored. Rev. ca4a0c2
