### ISSUE TITLE
Missing implementation for routine adjust_start_frame.MICRODVD_SUBTITLE_ITEM

### ISSUE THREAD

**Issue by nmaguirre** [nmaguirre/eiffel-subtitle-converter#7]
Routine adjust_start_frame from class MICRODVD_SUBTITLE_ITEM has an empty implementation. This routine must be implemented, guided by its textual description.

**Comment by gamassimino** [comment]
solved in rev. 417b380

**Comment by nmaguirre** [comment]
Please, to make it more readable, leave a blank space between assignee variable and :=, and := the assigned expression. Removing the 'resolved' tag for the moment.

**Comment by gamassimino** [comment]
fixed in rev. 4affd9e

**Comment by nmaguirre** [comment]
Well done!
