### ISSUE TITLE
Missing unit tests for routine MICRODVD_SUBTITLE.repOk

### ISSUE THREAD

**Issue by ibongiovanni** [nmaguirre/eiffel-subtitle-converter#70]
Routine repOk from class MICRODVD_SUBTITLE has no unit tests to assess its behaviour. At least one "positive" unit test must be provided for this routine. In this context, 'positive' is a test that evaluates the correct behaviour of the routine when right arguments are passed, while 'negative' refers to tests that check that the routine correctly controls ill-formed direct or indirect inputs.

**Comment by ibongiovanni** [comment]
test implemented in rev 6a9a978

**Comment by ibongiovanni** [comment]
an updated version implemented on rev d5e5f3c

**Comment by ibongiovanni** [comment]
Two new tests added in rev 70c0f8e

**Comment by nricci** [comment]
Thanks!
