### ISSUE TITLE
Missing precondition for routine MICRODVD_SUBTITLE.flush

### ISSUE THREAD

**Issue by gamassimino** [nmaguirre/eiffel-subtitle-converter#71]

**Comment by gamassimino** [comment]
solved in rev. 7d8edfa

**Comment by nmaguirre** [comment]
Precondition of flush is wrong, it refers to a non existent feature. Please correct asap. Removing 'resolved' tag.

**Comment by gamassimino** [comment]
I'm not sure but the precondition culd be true?

**Comment by ibongiovanni** [comment]
I think precondition could be "items /= Void"

**Comment by gamassimino** [comment]
I deleted the precondition but added an invariant for the class
solved in rev. 9832e02

**Comment by gamassimino** [comment]
sorry, the correct #commit is 844b9bc

**Comment by nricci** [comment]
Seems ok. Thanks!
