### ISSUE TITLE
Missing postcondition for routine make.MICRODVD_SUBTITLE

### ISSUE THREAD

**Issue by damarisg** [nmaguirre/eiffel-subtitle-converter#72]

**Comment by nmaguirre** [comment]
Implementation is wrong, it does not compile. Please compile before committing. repOK.make does not make any sense. Please correct.

**Comment by damarisg** [comment]
I assign the postcondition make.MICRODVD_SUBTITLE , the implementation make.MICRODVD_SUBTITLE  is the issue #27.

**Comment by damarisg** [comment]
Solved in rev. ee94a8c

**Comment by nricci** [comment]
Thanks
