### ISSUE TITLE
Missing postcondition for routine SUBRIP_SUBTITLE_TIME.move_forward

### ISSUE THREAD

**Issue by gamassimino** [nmaguirre/eiffel-subtitle-converter#76]

**Comment by gamassimino** [comment]
solved in rev. 1e7fbef

**Comment by GastonPalandri** [comment]
Change the postcondicion, the solution is "hours = (old hours) - offset_milliseconds//3600000".
Change in all postcondition the routine.

**Comment by gamassimino** [comment]
fixed in rev. fa127db

**Comment by nricci** [comment]
There is a special test failing (test_set_move_forward_valid_time). I thinks the test is good and if you debug it you will se that it fails on the postcondition. The implementation computes the right value asserted in the test. I thinks that somehow the post is asking for something different and it's making the feature fail even though it is correct. Make sure that the post asserts the right property.

**Comment by gamassimino** [comment]
I don't know if I can use the local features "remainder_hours" and "remainder_minutes" in the postcondition so I remplaces their values but I don't know if is right
fixed in rev. 24888ae

**Comment by nricci** [comment]
No, using "reminder_hours" in the post would be out of scope, and thus result in a compilation error. But it's okay as it is now. The falling test is now passing. Thanks.
