### ISSUE TITLE
Missing unit tests for routine adjust_start_frame.MICRODVD_SUBTITLE_ITEM

### ISSUE THREAD

**Issue by nmaguirre** [nmaguirre/eiffel-subtitle-converter#8]
Routine adjust_start_frame from class MICRODVD_SUBTITLE_ITEM has no unit tests to assess its behaviour. At least one unit "positive" and one "negative" unit test must be provided for this routine. In this context, 'positive' is a test that evaluates the correct behaviour of the routine when right arguments are passed, while 'negative' refers to tests that check that the routine correctly controls ill-formed direct or indirect inputs. 

Please use a fine grained granularity for the tests. If you want to assert several things on the same situation, please provide different tests for each assert. See tests for make.MICRODVD_SUBTITLE_ITEM for an example.

**Comment by sigarcia** [comment]
Solved in rev. 3d039e7

**Comment by sigarcia** [comment]
Solved in rev. 701950c

**Comment by nmaguirre** [comment]
In the "positive" test case, please use a valid value different from 0. Thanks!

**Comment by sigarcia** [comment]
Solved in rev. 2d8ad8d
