### ISSUE TITLE
Missing postcondition for routine SUBRIP_SUBTITLE_TIME.rewind

### ISSUE THREAD

**Issue by nicoboccolini** [nmaguirre/eiffel-subtitle-converter#81]

**Comment by nicoboccolini** [comment]
solved in rev. 6345ec3e8b3675de72cc845eb6ffa5c66bb5d8e3

**Comment by nicoboccolini** [comment]
fixed in rev. c00a54985dd6a28e1a2138a96d21b8a791bc0f7b

**Comment by nricci** [comment]
Well done. One suggestion though: given that the postcondition is so long, perhaps it would be a good idea to split it in various clauses with separate labels. Something like:

ensure
          valid_hour: <condition for hour>
          valid_minute: <condition for minute>

and so on...

Do this whenever posible. This improves readability and proves very useful when debugging.

**Comment by nicoboccolini** [comment]
Thanks! Fixed in rev. 7c3145a236039403661f668f71e75d103c679d94

**Comment by nricci** [comment]
Great! Thanks!
