### ISSUE TITLE
Missing invariant for class SUBRIP_SUBTITLE_TIME

### ISSUE THREAD

**Issue by dromero19** [nmaguirre/eiffel-subtitle-converter#82]

**Comment by dromero19** [comment]
Solved in rev. 0a46513

**Comment by rdegiovanni** [comment]
well done!

**Comment by saiema** [comment]
There is no need for hours to be < 24. Please correct the invariant to allow hours >= 24 (That is hours >= 0).

**Comment by dromero19** [comment]
Fixed in rev. 74b0ac3.
