### ISSUE TITLE
Missing precondition for routine adjust_start_frame.MICRODVD_SUBTITLE_ITEM

### ISSUE THREAD

**Issue by nmaguirre** [nmaguirre/eiffel-subtitle-converter#9]
Routine adjust_start_frame from class MICRODVD_SUBTITLE_ITEM has no explicit precondition. This routine must have a specific, explicit, precondition, indicating the acceptable new value as a start frame.

**Comment by ibongiovanni** [comment]
Resolved in rev 3b8c687

**Comment by nmaguirre** [comment]
Please notice that new_start_frame cannot be greater than or equal to the stop_frame. Please correct. I'm removing the 'resolved' tag.

**Comment by ibongiovanni** [comment]
Solved in rev c6ffcde

**Comment by nmaguirre** [comment]
Well done!
