### ISSUE TITLE
Missing implementation for routine remove_items.SUBRIP_SUBTITLE

### ISSUE THREAD

**Issue by nicodomgz** [nmaguirre/eiffel-subtitle-converter#94]

**Comment by nicodomgz** [comment]
Solved in rev.  01a4927

**Comment by andruvetto** [comment]
Project does not compile. Please correct asap. start_frame is not definited for SUBRIP_SUBTITLE

**Comment by nicodomgz** [comment]
Solved in rev. 0fbf095

**Comment by nricci** [comment]
Seems ok as a first version, however there are no good tests for this routine. I have suggested that more tests are implemented. As for now I'm going to close the issue. But probably we will have to reopen it if the implementation turns out not to work properly.
