### ISSUE TITLE
Missing poscondition for routine adjust_stop_timeSUBRIP_SUBTITLE_ITEM

### ISSUE THREAD

**Issue by dastorga** [nmaguirre/eiffel-subtitle-converter#97]

**Comment by rdegiovanni** [comment]
Your are using = to compare two SUBRIP_SUBTITLE_TIME objects. You should use the is_equal routine.
In addition, remember to include the link to the revision where you solve the issue when adding the label resolved.

**Comment by dastorga** [comment]
Sorry!
Solved in c09ed44b8dd5a4c7ab70432c8de8e3044b5ba6c4

**Comment by nricci** [comment]
Thanks
